# Build settings
title: "R&D Documentation"
### Built settings ###

url: "https://vanamsandeep-test.github.io"
baseurl: "/testrepo"

github_username: vanamsandeep
remote_theme: pages-themes/leap-day@v0.2.0
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
plantuml:
    raise_errors: true
plugins:
  - jekyll-timeago
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-default-layout
  - jemoji
  - jekyll-diagrams
  - jekyll-plantuml
