name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initial JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - run: $ sudo apt install default-jre
          
      - run: java -version    
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
        
      - uses: actions/checkout@v3    
      - uses: ruby/setup-ruby@v1      
        with:
          ruby-version: '2.7.0' # Not needed with a .ruby-version file 
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
          
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-    
          
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: 'docs' 
          jekyll_build_options: --trace
    
    
